### ISSUE TITLE
Failed to load dropcaster, cannot load octokit

### ISSUE THREAD

**Issue by AnthonyMastrean** [nerab/dropcaster#24]
I setup a simple Gemfile

```
source 'https://rubygems.org' do
  gem 'dropcaster'
end
```

And installed with Bundler

```
$ bundle install
```

But, I get a failed to load error when running dropcaster

```
$ bundle exec dropcaster
bundler: failed to load command: dropcaster (/usr/local/bundle/bin/dropcaster)
LoadError: cannot load such file -- octokit
  /usr/local/bundle/gems/dropcaster-0.0.7/lib/dropcaster/contributors.rb:1:in `require'
  /usr/local/bundle/gems/dropcaster-0.0.7/lib/dropcaster/contributors.rb:1:in `<top (required)>'
  /usr/local/bundle/gems/dropcaster-0.0.7/lib/dropcaster.rb:13:in `require'
  /usr/local/bundle/gems/dropcaster-0.0.7/lib/dropcaster.rb:13:in `<top (required)>'
  /usr/local/bundle/gems/dropcaster-0.0.7/bin/dropcaster:27:in `require'
  /usr/local/bundle/gems/dropcaster-0.0.7/bin/dropcaster:27:in `<top (required)>'
  /usr/local/bundle/bin/dropcaster:17:in `load'
  /usr/local/bundle/bin/dropcaster:17:in `<top (required)>'
```

The `contributors` file in the command source [requires a dependency](https://github.com/nerab/dropcaster/blob/master/lib/dropcaster/contributors.rb#L1) that you currently have marked as [a development dependency](https://github.com/nerab/dropcaster/blob/master/dropcaster.gemspec#L39).

I think it just needs to be moved to the regular dependency set. If I add that specific gem to my Gemfile and reinstall and execute, it works fine.

**Comment by nerab** [comment]
Thanks for the report. I am looking into it right now.
