### ISSUE TITLE
Issue with new version of activesupport

### ISSUE THREAD

**Issue by julianhinz** [nerab/dropcaster#244]
After fresh install of dropcaster I get this error:

```
Traceback (most recent call last):
	13: from /usr/local/lib/ruby/gems/2.7.0/bin/dropcaster:23:in `<main>'
	12: from /usr/local/lib/ruby/gems/2.7.0/bin/dropcaster:23:in `load'
	11: from /usr/local/lib/ruby/gems/2.7.0/gems/dropcaster-1.1.0/bin/dropcaster:29:in `<top (required)>'
	10: from /usr/local/Cellar/ruby@2.7/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 9: from /usr/local/Cellar/ruby@2.7/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 8: from /usr/local/lib/ruby/gems/2.7.0/gems/dropcaster-1.1.0/lib/dropcaster.rb:6:in `<top (required)>'
	 7: from /usr/local/Cellar/ruby@2.7/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 6: from /usr/local/Cellar/ruby@2.7/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 5: from /usr/local/lib/ruby/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/core_ext/date_time/conversions.rb:5:in `<top (required)>'
	 4: from /usr/local/Cellar/ruby@2.7/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 3: from /usr/local/Cellar/ruby@2.7/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 2: from /usr/local/lib/ruby/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/core_ext/time/conversions.rb:6:in `<top (required)>'
	 1: from /usr/local/lib/ruby/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/core_ext/time/conversions.rb:72:in `<class:Time>'
/usr/local/lib/ruby/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/core_ext/time/conversions.rb:72:in `alias_method': undefined method `xmlschema' for class `Time' (NameError)
```

If I manually uninstall `activesupport-6.1.0` and install `activesupport-6.0.0` all works fine. This issue here seems to be related: https://github.com/rails/rails/issues/40861

**Comment by terotil** [comment]
Solved this for me by adding explicit version for `activesupport` in my podcast project `Gemfile`
```
source 'https://rubygems.org'

gem 'activesupport', '6.0.0'
gem 'dropcaster'
```

**Comment by nerab** [comment]
Please re-open if the problem still persists.
