### ISSUE TITLE
else without rescue is useless

### ISSUE THREAD

**Issue by nerab** [nerab/dropcaster#4]
computer:~ jdoe$ cd /tmp/files
    computer:files jdoe$ ls
    channel.yml     hpr1143.mp3
    computer:files jdoe$
    computer:files jdoe$ cat channel.yml
        :title: 'All About Everything'
        :subtitle: 'A show about everything'
        :url: 'http://www.example.com/podcasts/everything/index.html'
    computer:files jdoe$
    computer:files jdoe$ gem install dropcaster
    Fetching: ruby-mp3info-0.8.gem (100%)
    Fetching: i18n-0.6.1.gem (100%)
    Fetching: multi_json-1.7.2.gem (100%)
    Fetching: activesupport-3.2.13.gem (100%)
    Fetching: dropcaster-0.0.4.gem (100%)
    Successfully installed ruby-mp3info-0.8
    Successfully installed i18n-0.6.1
    Successfully installed multi_json-1.7.2
    Successfully installed activesupport-3.2.13
    Successfully installed dropcaster-0.0.4
    5 gems installed
    Installing ri documentation for ruby-mp3info-0.8...
    Installing ri documentation for i18n-0.6.1...
    Installing ri documentation for multi_json-1.7.2...
    Installing ri documentation for activesupport-3.2.13...
    Installing ri documentation for dropcaster-0.0.4...
    Installing RDoc documentation for ruby-mp3info-0.8...
    Installing RDoc documentation for i18n-0.6.1...
    Installing RDoc documentation for multi_json-1.7.2...
    Installing RDoc documentation for activesupport-3.2.13...
    Installing RDoc documentation for dropcaster-0.0.4...
    computer:files jdoe$
    computer:files jdoe$ dropcaster
    /Users/jdoe/.rvm/gems/ruby-1.9.3-p327/gems/dropcaster-0.0.4/lib/dropcaster/channel.rb:156:
    warning: else without rescue is useless
    /Users/jdoe/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in
    `require': /Users/jdoe/.rvm/gems/ruby-1.9.3-p327/gems/dropcaster-0.0.4/lib/dropcaster/channel.rb:151:
    syntax error, unexpected ':', expecting keyword_then or ',' or ';' or
    '\n' (SyntaxError)
            when nil   : nil
                        ^
    /Users/jdoe/.rvm/gems/ruby-1.9.3-p327/gems/dropcaster-0.0.4/lib/dropcaster/channel.rb:153:
    syntax error, unexpected keyword_when, expecting keyword_end
            when false : 'No'
                ^
    /Users/jdoe/.rvm/gems/ruby-1.9.3-p327/gems/dropcaster-0.0.4/lib/dropcaster/channel.rb:159:
    syntax error, unexpected keyword_end, expecting $end
            from /Users/jdoe/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
            from /Users/jdoe/.rvm/gems/ruby-1.9.3-p327/gems/dropcaster-0.0.4/lib/dropcaster.rb:15:in `<top (required)>'
            from /Users/jdoe/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
            from /Users/jdoe/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
            from /Users/jdoe/.rvm/gems/ruby-1.9.3-p327/gems/dropcaster-0.0.4/bin/dropcaster:28:in `<top (required)>'
            from /Users/jdoe/.rvm/gems/ruby-1.9.3-p327/bin/dropcaster:19:in `load'
            from /Users/jdoe/.rvm/gems/ruby-1.9.3-p327/bin/dropcaster:19:in `<main>'
            from /Users/jdoe/.rvm/gems/ruby-1.9.3-p327/bin/ruby_noexec_wrapper:14:in `eval'
            from /Users/jdoe/.rvm/gems/ruby-1.9.3-p327/bin/ruby_noexec_wrapper:14:in `<main>'
    computer:files jdoe$

**Comment by nerab** [comment]
Fixed with 74b71673838bc79f568dbdf0824b41a660f16fba
